import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import PDFDocument from 'pdfkit';
import sharp from 'sharp';

// ===== CONFIG =====
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const PUBLIC = path.join(ROOT, 'public');
const IMAGES_BASE = path.join(PUBLIC, 'images', 'Categorias');
const LOGO_PATH = path.join(PUBLIC, 'images', 'Branding', 'B2 B2YOU Header Landscape 2.png');
const LOGO_WHITE_PATH = path.join(PUBLIC, 'images', 'Branding', 'B2YOU-logo-white.jpg');
const OUTPUT_PATH = path.join(PUBLIC, 'catalogo-b2you.pdf');

// Fonts
const FONTS_DIR = path.join(__dirname, 'fonts');
const FONT_REGULAR = path.join(FONTS_DIR, 'Inter-Regular.ttf');
const FONT_BOLD = path.join(FONTS_DIR, 'Inter-Bold.ttf');
const FONT_MEDIUM = path.join(FONTS_DIR, 'Inter-Medium.ttf');
const FONT_ITALIC = path.join(FONTS_DIR, 'Inter-MediumItalic.ttf');

// Brand colors
const COGNAC = [122, 79, 72];
const COGNAC_DARK = [95, 60, 54];
const BLACK = [45, 45, 45];
const GRAY = [90, 90, 90];
const LIGHT_GRAY = [163, 163, 163];
const CREAM = [250, 250, 249];
const WHITE = [255, 255, 255];
const BORDER = [229, 229, 229];

// Layout
const PAGE_W = 595.28;
const PAGE_H = 841.89;
const MARGIN = 36;
const CONTENT_W = PAGE_W - MARGIN * 2;

// Background removal cache (pre-generated by remove-backgrounds.js)
const BG_CACHE_DIR = path.join(__dirname, '.bg-cache');

function getBgRemovedPath(imgPath) {
  const key = path.basename(imgPath).replace(/[^a-zA-Z0-9.]/g, '_') + '_' +
    fs.statSync(imgPath).size + '.png';
  const cachePath = path.join(BG_CACHE_DIR, key);
  return fs.existsSync(cachePath) ? cachePath : imgPath;
}

// ===== HELPERS =====

function parseMetadata(text) {
  const metadata = {};
  text.trim().split('\n').forEach(line => {
    const [key, ...valueParts] = line.split(':');
    if (key && valueParts.length) {
      const k = key.trim().toLowerCase();
      const v = valueParts.join(':').trim();
      if (k === 'images' || k === 'videos') {
        metadata[k] = v.split(',').map(i => i.trim()).filter(Boolean);
      } else {
        metadata[k] = v;
      }
    }
  });
  return metadata;
}

function formatPrice(num) {
  return '$' + Number(num).toLocaleString('es-AR');
}

async function loadProducts() {
  const manifestPath = path.join(PUBLIC, 'manifest-catalogo.json');
  const manifestRaw = JSON.parse(fs.readFileSync(manifestPath, 'utf-8'));
  const dimensionImages = manifestRaw._dimension_images || {};
  const manifest = Object.fromEntries(
    Object.entries(manifestRaw).filter(([k]) => !k.startsWith('_'))
  );
  const products = [];
  for (const [category, items] of Object.entries(manifest)) {
    for (const productName of items) {
      const productDir = path.join(IMAGES_BASE, category, productName);
      const metaPath = path.join(productDir, 'metadata.txt');
      if (!fs.existsSync(metaPath)) {
        console.warn(`  Skipping ${category}/${productName} — no metadata.txt`);
        continue;
      }
      const meta = parseMetadata(fs.readFileSync(metaPath, 'utf-8'));
      const images = (meta.images || [])
        .map(img => path.join(productDir, img))
        .filter(p => fs.existsSync(p));
      const dimImgs = (dimensionImages[productName] || []).map(f => f.toLowerCase());
      products.push({ category, productName, ...meta, imagePaths: images, dimImgs });
    }
  }
  return products;
}

async function prepareImage(imgPath, maxW, maxH, { bg = null, cover = false, trim: doTrim = false } = {}) {
  try {
    let pipeline = sharp(imgPath);
    if (bg) pipeline = pipeline.flatten({ background: bg });
    if (doTrim) pipeline = pipeline.trim({ threshold: 30 });
    const fit = cover ? 'cover' : 'inside';
    const buffer = await pipeline
      .resize(Math.round(maxW * 2), Math.round(maxH * 2), { fit, withoutEnlargement: false })
      .jpeg({ quality: 88 })
      .toBuffer();
    return buffer;
  } catch { return null; }
}

async function getImageDimensions(imgPath) {
  try {
    const meta = await sharp(imgPath).metadata();
    return { width: meta.width, height: meta.height, aspect: meta.width / meta.height };
  } catch { return { width: 1, height: 1, aspect: 1 }; }
}

// ===== PDF GENERATION =====

async function generate() {
  console.log('Loading products...');
  const products = await loadProducts();
  console.log(`Found ${products.length} products.`);

  // Group by category
  const grouped = {};
  for (const p of products) {
    if (!grouped[p.category]) grouped[p.category] = [];
    grouped[p.category].push(p);
  }

  const doc = new PDFDocument({ size: 'A4', margin: 0, bufferPages: true });
  const stream = fs.createWriteStream(OUTPUT_PATH);
  doc.pipe(stream);

  // ===== COVER PAGE =====
  doc.rect(0, 0, PAGE_W, PAGE_H).fill(COGNAC);
  doc.rect(0, 0, PAGE_W, 60).fill(COGNAC_DARK);
  doc.rect(0, PAGE_H - 60, PAGE_W, 60).fill(COGNAC_DARK);

  // White logo
  const origLogoMeta = await sharp(LOGO_PATH).metadata();
  const negatedLogo = await sharp(LOGO_PATH).negate({ alpha: false }).toBuffer();
  const coverLogoBuffer = await sharp({
    create: { width: origLogoMeta.width, height: origLogoMeta.height, channels: 4,
      background: { r: COGNAC[0], g: COGNAC[1], b: COGNAC[2], alpha: 255 } }
  }).composite([{ input: negatedLogo, blend: 'over' }]).jpeg({ quality: 90 }).toBuffer();

  const logoAspect = origLogoMeta.width / origLogoMeta.height;
  const logoDispW = 320;
  const logoX = (PAGE_W - logoDispW) / 2;
  doc.image(coverLogoBuffer, logoX, PAGE_H * 0.26, { width: logoDispW });

  doc.moveTo(PAGE_W / 2 - 80, PAGE_H * 0.46).lineTo(PAGE_W / 2 + 80, PAGE_H * 0.46)
    .lineWidth(0.8).strokeColor(WHITE).stroke();
  doc.fontSize(44).font(FONT_BOLD).fillColor(WHITE)
    .text('CATÁLOGO', 0, PAGE_H * 0.48, { align: 'center', width: PAGE_W });
  doc.fontSize(14).font(FONT_REGULAR).fillColor(CREAM)
    .text('Accesorios Premium para tu Marca', 0, PAGE_H * 0.55, { align: 'center', width: PAGE_W });
  doc.moveTo(PAGE_W / 2 - 80, PAGE_H * 0.59).lineTo(PAGE_W / 2 + 80, PAGE_H * 0.59)
    .lineWidth(0.8).strokeColor(WHITE).stroke();
  doc.fontSize(12).font(FONT_REGULAR).fillColor(WHITE)
    .text(new Date().getFullYear().toString(), 0, PAGE_H * 0.62, { align: 'center', width: PAGE_W });

  // ===== CATEGORY SEPARATOR PAGES + PRODUCT PAGES =====
  const categories = Object.keys(grouped);
  const darkPages = new Set(); // track pages with dark background
  darkPages.add(0); // cover page

  for (const category of categories) {
    const catProducts = grouped[category];

    // Category separator page
    doc.addPage({ size: 'A4', margin: 0 });
    darkPages.add(doc.bufferedPageRange().count - 1);
    doc.rect(0, 0, PAGE_W, PAGE_H).fill(COGNAC_DARK);
    doc.rect(0, PAGE_H - 8, PAGE_W, 8).fill(COGNAC);
    doc.fontSize(32).font(FONT_BOLD).fillColor(WHITE)
      .text(category.toUpperCase(), MARGIN, PAGE_H * 0.45, { width: CONTENT_W, align: 'center' });

    // Each product gets 1 page
    for (const product of catProducts) {
      await drawProductPage(doc, product);
    }
  }

  // ===== FOOTERS =====
  const range = doc.bufferedPageRange();
  const totalPages = range.count;

  // Prepare footer logos — dark (original) and white (for dark pages)
  const footerLogoDark = await sharp(LOGO_PATH)
    .resize(120, 28, { fit: 'inside', withoutEnlargement: true })
    .png().toBuffer().catch(() => null);

  // White logo (pre-generated)
  const footerLogoWhite = await sharp(LOGO_WHITE_PATH)
    .resize(120, 28, { fit: 'inside', withoutEnlargement: true })
    .jpeg({ quality: 90 }).toBuffer();

  const origAddPage = doc.addPage.bind(doc);
  doc.addPage = () => doc;

  for (let i = 0; i < totalPages; i++) {
    doc.switchToPage(i);
    if (i === 0) continue; // skip cover

    const isDark = darkPages.has(i);
    const footerY = PAGE_H - 28;
    doc.rect(MARGIN, footerY - 4, CONTENT_W, 0.5).fill(isDark ? [255, 255, 255, 0.2] : BORDER);

    const logo = isDark ? footerLogoWhite : footerLogoDark;
    if (logo) doc.image(logo, MARGIN, footerY, { height: 11 });

    doc.fontSize(8).font(FONT_REGULAR).fillColor(isDark ? [255, 255, 255] : LIGHT_GRAY)
      .text(`${i} / ${totalPages - 1}`, MARGIN, footerY + 1, { width: CONTENT_W, align: 'right', lineBreak: false });
  }

  doc.addPage = origAddPage;
  doc.end();

  await new Promise(resolve => stream.on('finish', resolve));
  console.log(`\nCatalog generated: ${OUTPUT_PATH}`);
  console.log(`Total pages: ${totalPages}`);
}

async function drawProductPage(doc, product) {
  const images = product.imagePaths || [];
  const hasMultipleImages = images.length > 1;
  const M = MARGIN;
  const CW = CONTENT_W;
  const titleText = product.title || product.productName;

  // ===== PAGE 1: HERO IMAGE + INFO =====
  doc.addPage({ size: 'A4', margin: 0 });
  doc.rect(0, 0, PAGE_W, PAGE_H).fill(WHITE);

  // Hero image — large, ~68% of page, trimmed to remove whitespace
  const heroTopY = 0;
  const heroH = PAGE_H * 0.68;

  if (images.length > 0) {
    // Trim whitespace around product, then fit into hero area
    const heroImg = await prepareImage(images[0], PAGE_W, heroH, { trim: true });
    if (heroImg) {
      // Get trimmed dimensions to center properly
      const trimmedMeta = await sharp(heroImg).metadata();
      const trimAspect = trimmedMeta.width / trimmedMeta.height;
      let dispW = PAGE_W;
      let dispH = dispW / trimAspect;
      if (dispH > heroH) { dispH = heroH; dispW = dispH * trimAspect; }
      const imgX = (PAGE_W - dispW) / 2;
      doc.image(heroImg, imgX, heroTopY + (heroH - dispH) / 2, { width: dispW });
    }
  }

  // Cognac strip
  let y = heroH + 4;
  doc.rect(M, y, CW, 3).fill(COGNAC);
  y += 12;

  // Title + Code
  if (product.code) {
    doc.fontSize(9).font(FONT_REGULAR).fillColor(LIGHT_GRAY)
      .text(product.code, M, y + 8, { width: CW, align: 'right', lineBreak: false });
  }
  doc.fontSize(28).font(FONT_BOLD).fillColor(BLACK)
    .text(titleText, M, y, { width: CW - 70 });
  y += doc.heightOfString(titleText, { width: CW - 70, fontSize: 28 }) + 3;

  // Subtitle
  if (product.subtitle) {
    doc.fontSize(12).font(FONT_ITALIC).fillColor(COGNAC)
      .text(product.subtitle, M, y, { width: CW });
    y += 18;
  }

  // Description
  if (product.description) {
    doc.fontSize(9.5).font(FONT_REGULAR).fillColor(GRAY)
      .text(product.description, M, y, { width: CW * 0.8, lineGap: 2.5 });
    y += doc.heightOfString(product.description, { width: CW * 0.8, fontSize: 9.5 }) + 10;
  }

  // Price — always show, "Consultar" if missing
  doc.roundedRect(M, y, CW, 34, 4).fill([248, 246, 244]);
  doc.fontSize(8).font(FONT_REGULAR).fillColor(GRAY)
    .text('MAYORISTA', M + 14, y + 6, { lineBreak: false });
  if (product.price_mayorista) {
    doc.fontSize(15).font(FONT_BOLD).fillColor(COGNAC)
      .text(formatPrice(product.price_mayorista), M + 14, y + 16, { lineBreak: false });
  } else {
    doc.fontSize(15).font(FONT_ITALIC).fillColor(LIGHT_GRAY)
      .text('Consultar', M + 14, y + 16, { lineBreak: false });
  }
  doc.fontSize(8).font(FONT_REGULAR).fillColor(GRAY)
    .text('MINORISTA', M + CW / 2, y + 6, { lineBreak: false });
  doc.fontSize(15).font(FONT_ITALIC).fillColor(LIGHT_GRAY)
    .text('Consultar', M + CW / 2, y + 16, { lineBreak: false });

  // ===== PAGE 2: GALLERY (only if multiple images) =====
  if (!hasMultipleImages) return;

  doc.addPage({ size: 'A4', margin: 0 });
  doc.rect(0, 0, PAGE_W, PAGE_H).fill(WHITE);
  doc.rect(0, 0, PAGE_W, 3).fill(COGNAC);

  const dimSet = new Set(product.dimImgs || []);
  function isDimImage(imgPath) {
    return dimSet.has(path.basename(imgPath).toLowerCase());
  }

  // Place image: cover for product photos, contain for dimension images
  async function placeImage(imgPath, x, y, w, h) {
    const isDim = isDimImage(imgPath);
    if (isDim) {
      // Contain — show full image without cropping
      const img = await prepareImage(imgPath, w, h);
      if (img) {
        const dims = await getImageDimensions(imgPath);
        let dw = w, dh = dw / dims.aspect;
        if (dh > h) { dh = h; dw = dh * dims.aspect; }
        doc.rect(x, y, w, h).fill([250, 250, 249]); // light bg
        doc.image(img, x + (w - dw) / 2, y + (h - dh) / 2, { width: dw });
      }
    } else {
      // Cover — zoom and crop
      const img = await prepareImage(imgPath, w, h, { cover: true });
      if (img) doc.image(img, x, y, { width: w, height: h });
    }
  }

  const extraImages = images.slice(1);
  const count = extraImages.length;
  const gap = 6;
  const pageContentH = PAGE_H - 38;

  if (count === 1) {
    await placeImage(extraImages[0], 0, 0, PAGE_W, pageContentH);

  } else if (count === 2) {
    const colW = (PAGE_W - gap) / 2;
    for (let i = 0; i < 2; i++) {
      await placeImage(extraImages[i], i * (colW + gap), 0, colW, pageContentH);
    }

  } else if (count === 3) {
    const leftW = PAGE_W * 0.55;
    const rightW = PAGE_W - leftW - gap;
    const rightH = (pageContentH - gap) / 2;
    await placeImage(extraImages[0], 0, 0, leftW, pageContentH);
    for (let i = 0; i < 2; i++) {
      await placeImage(extraImages[1 + i], leftW + gap, i * (rightH + gap), rightW, rightH);
    }

  } else if (count === 4) {
    const colW = (PAGE_W - gap) / 2;
    const rowH = (pageContentH - gap) / 2;
    for (let i = 0; i < 4; i++) {
      const col = i % 2, row = Math.floor(i / 2);
      await placeImage(extraImages[i], col * (colW + gap), row * (rowH + gap), colW, rowH);
    }

  } else {
    const topH = pageContentH * 0.55;
    const botH = pageContentH - topH - gap;
    const topCount = Math.min(2, count);
    const topW = (PAGE_W - gap * (topCount - 1)) / topCount;
    for (let i = 0; i < topCount; i++) {
      await placeImage(extraImages[i], i * (topW + gap), 0, topW, topH);
    }
    const botImages = extraImages.slice(topCount);
    const botCount = Math.min(botImages.length, 4);
    const botW = (PAGE_W - gap * (botCount - 1)) / botCount;
    for (let i = 0; i < botCount; i++) {
      await placeImage(botImages[i], i * (botW + gap), topH + gap, botW, botH);
    }
  }
}

generate().catch(err => {
  console.error('Error generating catalog:', err);
  process.exit(1);
});
