import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import PDFDocument from 'pdfkit';
import sharp from 'sharp';
import { PAYMENT_TERMS, normalizeProveedor } from '../utils/paymentTerms.js';

// ===== CONFIG =====
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const PUBLIC = path.join(ROOT, 'public');
const IMAGES_BASE = path.join(PUBLIC, 'images', 'Categorias');
const LOGO_PATH = path.join(PUBLIC, 'images', 'Branding', 'B2 B2YOU Header Landscape 2.png');
const LOGO_WHITE_PATH = path.join(PUBLIC, 'images', 'Branding', 'B2YOU-logo-white.jpg');
const OUTPUT_PATH = path.join(PUBLIC, 'catalogo-b2you.pdf');

// Fonts. Body/labels stay in Inter; display + titles use Fraunces, the brand
// serif from the website (pdfkit/fontkit reads the .woff directly).
const FONTS_DIR = path.join(__dirname, 'fonts');
const FONT_REGULAR = path.join(FONTS_DIR, 'Inter-Regular.ttf');
const FONT_BOLD = path.join(FONTS_DIR, 'Inter-Bold.ttf');
const FONT_MEDIUM = path.join(FONTS_DIR, 'Inter-Medium.ttf');
const FONT_ITALIC = path.join(FONTS_DIR, 'Inter-MediumItalic.ttf');
const FR_DIR = path.join(ROOT, 'node_modules', '@fontsource', 'fraunces', 'files');
const FONT_DISPLAY = path.join(FR_DIR, 'fraunces-latin-600-normal.woff');
const FONT_DISPLAY_ITALIC = path.join(FR_DIR, 'fraunces-latin-500-italic.woff');

// Brand colors
const COGNAC = [122, 79, 72];
const COGNAC_DARK = [95, 60, 54];
const BLACK = [45, 45, 45];
const GRAY = [90, 90, 90];
const LIGHT_GRAY = [163, 163, 163];
const CREAM = [250, 250, 249];
const CREAM_DIM = [220, 204, 197];
const WHITE = [255, 255, 255];
const BORDER = [229, 229, 229];

// ===== PURCHASE CONDITIONS (color-coded) =====
// Each product carries a coloured dot matching one of these groups; the legend
// at the end of the catalog maps colour -> conditions. We NEVER print the
// supplier name or contact: the colour abstracts the supplier away.
const CONDITIONS = [
  { key: 'aston',  color: [90, 118, 134],  terms: PAYMENT_TERMS.aston.terms },   // slate
  { key: 'saxs',   color: [118, 134, 102], terms: PAYMENT_TERMS.saxs.terms },    // sage
  { key: 'javera', color: [146, 100, 120], terms: PAYMENT_TERMS.javera.terms },  // plum
  { key: '_other', color: [150, 142, 134], terms: ['Coordinamos las condiciones de compra por WhatsApp.'] }, // taupe
];
function conditionFor(proveedor) {
  const key = normalizeProveedor(proveedor);
  return CONDITIONS.find(c => c.key === key) || CONDITIONS[CONDITIONS.length - 1];
}

// Belt género + origen (from the product tags), as display strings.
function beltAttributes(product) {
  const tags = String(product.tags || '').split(',').map(t => t.trim().toLowerCase());
  const has = t => tags.includes(t);
  const out = [];
  const genero = has('hombre') && has('mujer') ? 'Hombre y mujer'
    : has('hombre') ? 'Hombre' : has('mujer') ? 'Mujer' : null;
  const origen = has('importado') && has('nacional') ? 'Importado y nacional'
    : has('importado') ? 'Importado' : has('nacional') ? 'Nacional' : null;
  if (genero) out.push(genero);
  if (origen) out.push(origen);
  return out;
}

// Draw a small outlined pill; returns its width for laying the next one out.
function drawAttrPill(doc, x, y, text) {
  const label = text.toUpperCase();
  doc.font(FONT_MEDIUM).fontSize(7.5);
  const w = doc.widthOfString(label) + 16;
  doc.roundedRect(x, y, w, 16, 8).lineWidth(0.7).strokeColor([201, 173, 167]).stroke();
  doc.fillColor(COGNAC).text(label, x + 8, y + 4.6, { lineBreak: false });
  return w;
}

// Layout
const PAGE_W = 595.28;
const PAGE_H = 841.89;
const MARGIN = 36;
const CONTENT_W = PAGE_W - MARGIN * 2;

// Background removal cache (pre-generated by remove-backgrounds.js)
const BG_CACHE_DIR = path.join(__dirname, '.bg-cache');

function getBgRemovedPath(imgPath) {
  const key = path.basename(imgPath).replace(/[^a-zA-Z0-9.]/g, '_') + '_' +
    fs.statSync(imgPath).size + '.png';
  const cachePath = path.join(BG_CACHE_DIR, key);
  return fs.existsSync(cachePath) ? cachePath : imgPath;
}

// ===== HELPERS =====

function parseMetadata(text) {
  const metadata = {};
  text.trim().split('\n').forEach(line => {
    const [key, ...valueParts] = line.split(':');
    if (key && valueParts.length) {
      const k = key.trim().toLowerCase();
      const v = valueParts.join(':').trim();
      if (k === 'images' || k === 'videos') {
        metadata[k] = v.split(',').map(i => i.trim()).filter(Boolean);
      } else {
        metadata[k] = v;
      }
    }
  });
  return metadata;
}

function formatPrice(num) {
  return '$' + Number(num).toLocaleString('es-AR');
}

async function loadProducts() {
  const manifestPath = path.join(PUBLIC, 'manifest-catalogo.json');
  const manifestRaw = JSON.parse(fs.readFileSync(manifestPath, 'utf-8'));
  const dimensionImages = manifestRaw._dimension_images || {};
  const manifest = Object.fromEntries(
    Object.entries(manifestRaw).filter(([k]) => !k.startsWith('_'))
  );
  const products = [];
  for (const [category, items] of Object.entries(manifest)) {
    for (const productName of items) {
      const productDir = path.join(IMAGES_BASE, category, productName);
      const metaPath = path.join(productDir, 'metadata.txt');
      if (!fs.existsSync(metaPath)) {
        console.warn(`  Skipping ${category}/${productName} - no metadata.txt`);
        continue;
      }
      const meta = parseMetadata(fs.readFileSync(metaPath, 'utf-8'));
      const images = (meta.images || [])
        .map(img => path.join(productDir, img))
        .filter(p => fs.existsSync(p));
      const dimImgs = (dimensionImages[productName] || []).map(f => f.toLowerCase());
      products.push({ category, productName, ...meta, imagePaths: images, dimImgs });
    }
  }
  return products;
}

async function prepareImage(imgPath, maxW, maxH, { bg = null, cover = false, trim: doTrim = false } = {}) {
  try {
    let pipeline = sharp(imgPath);
    if (bg) pipeline = pipeline.flatten({ background: bg });
    if (doTrim) pipeline = pipeline.trim({ threshold: 30 });
    const fit = cover ? 'cover' : 'inside';
    const buffer = await pipeline
      .resize(Math.round(maxW * 2), Math.round(maxH * 2), { fit, withoutEnlargement: false })
      .jpeg({ quality: 88 })
      .toBuffer();
    return buffer;
  } catch { return null; }
}

async function getImageDimensions(imgPath) {
  try {
    const meta = await sharp(imgPath).metadata();
    return { width: meta.width, height: meta.height, aspect: meta.width / meta.height };
  } catch { return { width: 1, height: 1, aspect: 1 }; }
}

// ===== PDF GENERATION =====

async function generate() {
  console.log('Loading products...');
  const products = await loadProducts();
  console.log(`Found ${products.length} products.`);

  // Group by category
  const grouped = {};
  for (const p of products) {
    if (!grouped[p.category]) grouped[p.category] = [];
    grouped[p.category].push(p);
  }

  const doc = new PDFDocument({ size: 'A4', margin: 0, bufferPages: true });
  const stream = fs.createWriteStream(OUTPUT_PATH);
  doc.pipe(stream);

  // ===== COVER PAGE =====
  doc.rect(0, 0, PAGE_W, PAGE_H).fill(COGNAC);
  doc.rect(0, PAGE_H - 96, PAGE_W, 96).fill(COGNAC_DARK); // grounding foot band

  // White logo (negate the dark landscape mark onto a cognac plate)
  const origLogoMeta = await sharp(LOGO_PATH).metadata();
  const negatedLogo = await sharp(LOGO_PATH).negate({ alpha: false }).toBuffer();
  const coverLogoBuffer = await sharp({
    create: { width: origLogoMeta.width, height: origLogoMeta.height, channels: 4,
      background: { r: COGNAC[0], g: COGNAC[1], b: COGNAC[2], alpha: 255 } }
  }).composite([{ input: negatedLogo, blend: 'over' }]).jpeg({ quality: 92 }).toBuffer();

  const logoDispW = 250;
  doc.image(coverLogoBuffer, (PAGE_W - logoDispW) / 2, PAGE_H * 0.30, { width: logoDispW });

  // Title in Fraunces (brand serif)
  doc.font(FONT_DISPLAY).fontSize(52).fillColor(CREAM)
    .text('Catálogo', 0, PAGE_H * 0.50, { align: 'center', width: PAGE_W });
  doc.moveTo(PAGE_W / 2 - 28, PAGE_H * 0.50 + 78).lineTo(PAGE_W / 2 + 28, PAGE_H * 0.50 + 78)
    .lineWidth(1).strokeColor(CREAM).stroke();
  doc.font(FONT_REGULAR).fontSize(10.5).fillColor(CREAM_DIM)
    .text('ACCESORIOS PARA MARCAS Y EMPRESAS', 0, PAGE_H * 0.50 + 92,
      { align: 'center', width: PAGE_W, characterSpacing: 2.5 });
  doc.font(FONT_REGULAR).fontSize(10).fillColor(CREAM)
    .text(`Edición ${new Date().getFullYear()}`, 0, PAGE_H - 58,
      { align: 'center', width: PAGE_W, characterSpacing: 1.5 });

  // ===== CATEGORY SEPARATOR PAGES + PRODUCT PAGES =====
  const categories = Object.keys(grouped);
  const darkPages = new Set(); // track pages with dark background
  darkPages.add(0); // cover page

  for (const category of categories) {
    const catProducts = grouped[category];

    // Category separator page
    doc.addPage({ size: 'A4', margin: 0 });
    darkPages.add(doc.bufferedPageRange().count - 1);
    doc.rect(0, 0, PAGE_W, PAGE_H).fill(COGNAC_DARK);
    doc.rect(0, PAGE_H - 8, PAGE_W, 8).fill(COGNAC);
    doc.font(FONT_DISPLAY).fontSize(42).fillColor(WHITE)
      .text(category, MARGIN, PAGE_H * 0.44, { width: CONTENT_W, align: 'center' });
    doc.moveTo(PAGE_W / 2 - 24, PAGE_H * 0.44 + 64).lineTo(PAGE_W / 2 + 24, PAGE_H * 0.44 + 64)
      .lineWidth(1).strokeColor(CREAM).stroke();
    const catCount = catProducts.length;
    doc.font(FONT_REGULAR).fontSize(10).fillColor(CREAM_DIM)
      .text(`${catCount} ${catCount === 1 ? 'producto' : 'productos'}`, MARGIN, PAGE_H * 0.44 + 76,
        { width: CONTENT_W, align: 'center', characterSpacing: 1.5 });

    // Each product gets 1 page
    for (const product of catProducts) {
      await drawProductPage(doc, product);
    }
  }

  // ===== CONDITIONS LEGEND (end of catalog) =====
  drawConditionsPage(doc);

  // ===== FOOTERS =====
  const range = doc.bufferedPageRange();
  const totalPages = range.count;

  // Prepare footer logos - dark (original) and white (for dark pages)
  const footerLogoDark = await sharp(LOGO_PATH)
    .resize(120, 28, { fit: 'inside', withoutEnlargement: true })
    .png().toBuffer().catch(() => null);

  // White logo (pre-generated)
  const footerLogoWhite = await sharp(LOGO_WHITE_PATH)
    .resize(120, 28, { fit: 'inside', withoutEnlargement: true })
    .jpeg({ quality: 90 }).toBuffer();

  const origAddPage = doc.addPage.bind(doc);
  doc.addPage = () => doc;

  for (let i = 0; i < totalPages; i++) {
    doc.switchToPage(i);
    if (i === 0) continue; // skip cover

    const isDark = darkPages.has(i);
    const footerY = PAGE_H - 28;
    doc.rect(MARGIN, footerY - 4, CONTENT_W, 0.5).fill(isDark ? [255, 255, 255, 0.2] : BORDER);

    const logo = isDark ? footerLogoWhite : footerLogoDark;
    if (logo) doc.image(logo, MARGIN, footerY, { height: 11 });

    doc.fontSize(8).font(FONT_REGULAR).fillColor(isDark ? [255, 255, 255] : LIGHT_GRAY)
      .text(`${i} / ${totalPages - 1}`, MARGIN, footerY + 1, { width: CONTENT_W, align: 'right', lineBreak: false });
  }

  doc.addPage = origAddPage;
  doc.end();

  await new Promise(resolve => stream.on('finish', resolve));
  console.log(`\nCatalog generated: ${OUTPUT_PATH}`);
  console.log(`Total pages: ${totalPages}`);
}

async function drawProductPage(doc, product) {
  const images = product.imagePaths || [];
  const hasMultipleImages = images.length > 1;
  const M = MARGIN;
  const CW = CONTENT_W;
  const titleText = product.title || product.productName;

  // ===== PAGE 1: HERO IMAGE + INFO =====
  doc.addPage({ size: 'A4', margin: 0 });
  doc.rect(0, 0, PAGE_W, PAGE_H).fill(WHITE);

  // Hero image - large, ~68% of page, trimmed to remove whitespace
  const heroTopY = 0;
  const heroH = PAGE_H * 0.64;

  if (images.length > 0) {
    // Trim whitespace around product, then fit into hero area
    const heroImg = await prepareImage(images[0], PAGE_W, heroH, { trim: true });
    if (heroImg) {
      // Get trimmed dimensions to center properly
      const trimmedMeta = await sharp(heroImg).metadata();
      const trimAspect = trimmedMeta.width / trimmedMeta.height;
      let dispW = PAGE_W;
      let dispH = dispW / trimAspect;
      if (dispH > heroH) { dispH = heroH; dispW = dispH * trimAspect; }
      const imgX = (PAGE_W - dispW) / 2;
      doc.image(heroImg, imgX, heroTopY + (heroH - dispH) / 2, { width: dispW });
    }
  }

  // ===== INFO BLOCK =====
  let y = heroH + 22;

  // Short cognac accent rule
  doc.rect(M, y, 40, 3).fill(COGNAC);
  y += 15;

  // Code (small, right-aligned, tabular)
  if (product.code) {
    doc.font(FONT_MEDIUM).fontSize(8.5).fillColor(LIGHT_GRAY)
      .text(product.code, M, y + 7, { width: CW, align: 'right', characterSpacing: 1, lineBreak: false });
  }

  // Title in Fraunces
  doc.font(FONT_DISPLAY).fontSize(27).fillColor(BLACK)
    .text(titleText, M, y, { width: CW - 80 });
  y += doc.heightOfString(titleText, { width: CW - 80 }) + 5;

  // Subtitle in Fraunces italic
  if (product.subtitle) {
    doc.font(FONT_DISPLAY_ITALIC).fontSize(12.5).fillColor(COGNAC)
      .text(product.subtitle, M, y, { width: CW });
    y += doc.heightOfString(product.subtitle, { width: CW }) + 9;
  }

  // Belt attributes: género + origen as small pills (Cinturones only)
  if (product.category === 'Cinturones') {
    const attrs = beltAttributes(product);
    if (attrs.length) {
      let px = M;
      for (const a of attrs) px += drawAttrPill(doc, px, y, a) + 6;
      y += 28;
    }
  }

  // Description
  if (product.description) {
    doc.font(FONT_REGULAR).fontSize(9.5).fillColor(GRAY)
      .text(product.description, M, y, { width: CW * 0.82, lineGap: 3 });
    y += doc.heightOfString(product.description, { width: CW * 0.82, lineGap: 3 }) + 15;
  }

  // Clean value line (prices are hidden site-wide; this is a public download,
  // so no numbers here). Left: price on request. Right: the core value prop.
  doc.moveTo(M, y).lineTo(M + CW, y).lineWidth(0.5).strokeColor(BORDER).stroke();
  y += 12;
  doc.font(FONT_MEDIUM).fontSize(9.5).fillColor(BLACK)
    .text('Consultá el precio', M, y, { lineBreak: false });
  // Condition colour dot + label, right-aligned (legend at the end of the catalog)
  const cond = conditionFor(product.proveedor);
  const condLabel = 'Condiciones de compra';
  doc.font(FONT_REGULAR).fontSize(9.5);
  const labelW = doc.widthOfString(condLabel);
  const labelX = M + CW - labelW;
  doc.circle(labelX - 11, y + 5, 3.5).fill(cond.color);
  doc.fillColor(GRAY).text(condLabel, labelX, y, { lineBreak: false });

  // ===== PAGE 2: GALLERY (only if multiple images) =====
  if (!hasMultipleImages) return;

  doc.addPage({ size: 'A4', margin: 0 });
  doc.rect(0, 0, PAGE_W, PAGE_H).fill(WHITE);
  doc.rect(0, 0, PAGE_W, 3).fill(COGNAC);

  const dimSet = new Set(product.dimImgs || []);
  function isDimImage(imgPath) {
    return dimSet.has(path.basename(imgPath).toLowerCase());
  }

  // Place image: cover for product photos, contain for dimension images
  async function placeImage(imgPath, x, y, w, h) {
    const isDim = isDimImage(imgPath);
    if (isDim) {
      // Contain - show full image without cropping
      const img = await prepareImage(imgPath, w, h);
      if (img) {
        const dims = await getImageDimensions(imgPath);
        let dw = w, dh = dw / dims.aspect;
        if (dh > h) { dh = h; dw = dh * dims.aspect; }
        doc.rect(x, y, w, h).fill([250, 250, 249]); // light bg
        doc.image(img, x + (w - dw) / 2, y + (h - dh) / 2, { width: dw });
      }
    } else {
      // Cover - zoom and crop
      const img = await prepareImage(imgPath, w, h, { cover: true });
      if (img) doc.image(img, x, y, { width: w, height: h });
    }
  }

  const extraImages = images.slice(1);
  const count = extraImages.length;
  const gap = 6;
  const pageContentH = PAGE_H - 38;

  if (count === 1) {
    await placeImage(extraImages[0], 0, 0, PAGE_W, pageContentH);

  } else if (count === 2) {
    const colW = (PAGE_W - gap) / 2;
    for (let i = 0; i < 2; i++) {
      await placeImage(extraImages[i], i * (colW + gap), 0, colW, pageContentH);
    }

  } else if (count === 3) {
    const leftW = PAGE_W * 0.55;
    const rightW = PAGE_W - leftW - gap;
    const rightH = (pageContentH - gap) / 2;
    await placeImage(extraImages[0], 0, 0, leftW, pageContentH);
    for (let i = 0; i < 2; i++) {
      await placeImage(extraImages[1 + i], leftW + gap, i * (rightH + gap), rightW, rightH);
    }

  } else if (count === 4) {
    const colW = (PAGE_W - gap) / 2;
    const rowH = (pageContentH - gap) / 2;
    for (let i = 0; i < 4; i++) {
      const col = i % 2, row = Math.floor(i / 2);
      await placeImage(extraImages[i], col * (colW + gap), row * (rowH + gap), colW, rowH);
    }

  } else {
    const topH = pageContentH * 0.55;
    const botH = pageContentH - topH - gap;
    const topCount = Math.min(2, count);
    const topW = (PAGE_W - gap * (topCount - 1)) / topCount;
    for (let i = 0; i < topCount; i++) {
      await placeImage(extraImages[i], i * (topW + gap), 0, topW, topH);
    }
    const botImages = extraImages.slice(topCount);
    const botCount = Math.min(botImages.length, 4);
    const botW = (PAGE_W - gap * (botCount - 1)) / botCount;
    for (let i = 0; i < botCount; i++) {
      await placeImage(botImages[i], i * (botW + gap), topH + gap, botW, botH);
    }
  }
}

// ===== CONDITIONS LEGEND PAGE =====
function drawConditionsPage(doc) {
  doc.addPage({ size: 'A4', margin: 0 });
  doc.rect(0, 0, PAGE_W, PAGE_H).fill(WHITE);
  doc.rect(0, 0, PAGE_W, 3).fill(COGNAC);

  const M = MARGIN, CW = CONTENT_W;
  let y = 66;
  doc.font(FONT_DISPLAY).fontSize(30).fillColor(BLACK)
    .text('Condiciones de compra', M, y, { width: CW });
  y += 42;

  const intro = 'Cada producto lleva un color que corresponde a una de estas condiciones. Los precios y la disponibilidad se confirman por WhatsApp.';
  doc.font(FONT_REGULAR).fontSize(10).fillColor(GRAY).text(intro, M, y, { width: CW * 0.86, lineGap: 3 });
  y += doc.heightOfString(intro, { width: CW * 0.86, lineGap: 3 }) + 28;

  const termsX = M + 32;
  const termsW = CW - 32;

  CONDITIONS.forEach((cond, idx) => {
    if (idx > 0) {
      doc.moveTo(M, y - 15).lineTo(M + CW, y - 15).lineWidth(0.5).strokeColor(BORDER).stroke();
    }
    // Colour swatch (matches the dot on every product of this group)
    doc.circle(M + 7, y + 6, 7).fill(cond.color);
    // Terms as a clean bullet list, bullets in the same colour
    let ty = y;
    for (const term of cond.terms) {
      doc.circle(termsX + 2, ty + 4.5, 1.4).fill(cond.color);
      doc.font(FONT_REGULAR).fontSize(9.5).fillColor(GRAY)
        .text(term, termsX + 10, ty, { width: termsW - 10, lineGap: 2.5 });
      ty += doc.heightOfString(term, { width: termsW - 10, lineGap: 2.5 }) + 5;
    }
    y = ty + 20;
  });
}

generate().catch(err => {
  console.error('Error generating catalog:', err);
  process.exit(1);
});
